### ISSUE TITLE
Docker - License Plate Reader not starting on GPU

### ISSUE THREAD

**Issue by DeFlanko** [codeproject/CodeProject.AI-ALPR#10]
**Area of Concern**
- [ ] Server
- [x] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [x] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Im unable to start the Licence Plate Reader module on GPU. 

**Expected behavior**
To have the License Plate Reader module start on GPU.

**Screenshots**

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.8.0]
 - OS: Docker - codeproject/ai-server:cuda12_2-2.8.0
 - System RAM [64Gb]
 - GPU (if available) [NVIDIA GeForce RTX 3070]
 - GPU RAM (if available)  [8Gb]
```log
Server version:   2.8
System:           Docker (Ubuntu 22.04.3 LTS)
Operating System: Linux (Ubuntu 22.04)
CPUs:             13th Gen Intel(R) Core(TM) i7-13700 (Intel)
                  1 CPU x 12 cores. 24 logical processors (x64)
GPU (Primary):    NVIDIA GeForce RTX 3070 (8 GiB) (NVIDIA) 
                  Driver: 566.14, CUDA: 11.5.119 (up to: 12.7), Compute: 8.6, cuDNN: 8.9.6
System RAM:       30 GiB
Platform:         Linux
BuildConfig:      Release
Execution Env:    Docker
Runtime Env:      Production
Runtimes installed:
  .NET runtime:     8.0.8
  .NET SDK:         Not found
  Default Python:   3.10.12
  Go:               Not found
  NodeJS:           Not found
  Rust:             Not found
Video adapter info:
System GPU info:
  GPU 3D Usage       4%
  GPU RAM Usage      3.8 GiB
Global Environment variables:
  CPAI_APPROOTPATH = <root>
  CPAI_PORT        = 32168
```

**Additional context**
Thank you @ChrisMaunder for helping me fix my Docker string:
```powershell
docker run --name CodeProject.AI-CUDA12 -d -p 32168:32168 --gpus all --mount type=bind,source=C:\ProgramData\CodeProject\AI\docker\data,target=/etc/codeproject/ai --mount type=bind,source=C:\ProgramData\CodeProject\AI\docker\modules,target=/app/modules --mount type=bind,source=C:\ProgramData\CodeProject\AI\docker\modules\ObjectDetectionYOLOv5-6.2\custom-models,target=/app/preinstalled-modules/ObjectDetectionYolo/custom-models,readonly codeproject/ai-server:cuda12_2-2.8.0
```
License Plate Reader Info:
```log
Module 'License Plate Reader' 3.3.0 (ID: ALPR)
Valid:            True
Module Path:      <root>/modules/ALPR
Module Location:  Internal
AutoStart:        True
Queue:            alpr_queue
Runtime:          python3.8
Runtime Location: Local
FilePath:         ALPR_adapter.py
Start pause:      3 sec
Parallelism:      0
LogVerbosity:     
Platforms:        all,!windows-arm64
GPU Libraries:    not installed
GPU:              use if supported
Accelerator:      
Half Precision:   enable
Environment Variables
   AUTO_PLATE_ROTATE            = True
   CROPPED_PLATE_DIR            = <root>/Server/wwwroot
   MIN_COMPUTE_CAPABILITY       = 6
   MIN_CUDNN_VERSION            = 7
   OCR_OPTIMAL_CHARACTER_HEIGHT = 60
   OCR_OPTIMAL_CHARACTER_WIDTH  = 30
   OCR_OPTIMIZATION             = True
   PLATE_CONFIDENCE             = 0.7
   PLATE_RESCALE_FACTOR         = 2
   PLATE_ROTATE_DEG             = 0
   REMOVE_SPACES                = False
   ROOT_PATH                    = <root>
   SAVE_CROPPED_PLATE           = False
Status Data:  {
  "inferenceDevice": "CPU",
  "inferenceLibrary": "",
  "canUseGPU": "false",
  "successfulInferences": 0,
  "failedInferences": 0,
  "numInferences": 0,
  "averageInferenceMs": 0
}
Started:      29 Nov 2024 5:14:56 PM Coordinated Universal Time
LastSeen:     29 Nov 2024 5:21:20 PM Coordinated Universal Time
Status:       Started
Requests:     0 (includes status calls)



Installation Log
2024-11-27 20:34:59: Setting verbosity to quiet
2024-11-27 20:34:59: Hi Docker! We will disable shared python installs for downloaded modules
2024-11-27 20:34:59: (No schemas means: we can't detect if you're in light or dark mode)
2024-11-27 20:34:59:              Installing CodeProject.AI Analysis Module                
2024-11-27 20:34:59: ======================================================================
2024-11-27 20:34:59:                    CodeProject.AI Installer                           
2024-11-27 20:34:59: ======================================================================
2024-11-27 20:34:59: 958.00 GiB of 1.03 TiB available on Docker (linux ubuntu x86_64 - linux)
2024-11-27 20:34:59: Installing xz-utils...
2024-11-27 20:35:00: E: Could not get lock /var/lib/apt/lists/lock. It is held by process 924 (apt-get)
2024-11-27 20:35:00: E: Unable to lock directory /var/lib/apt/lists/
2024-11-27 20:35:00: Reading package lists...
2024-11-27 20:35:00: Building dependency tree...
2024-11-27 20:35:00: Reading state information...
2024-11-27 20:35:00: 0 upgraded, 0 newly installed, 0 to remove and 109 not upgraded.
2024-11-27 20:35:00: General CodeProject.AI setup                                          
2024-11-27 20:35:00: Setting permissions on runtimes folder...done
2024-11-27 20:35:00: Setting permissions on downloads folder...done
2024-11-27 20:35:00: Setting permissions on modules download folder...done
2024-11-27 20:35:00: Setting permissions on models download folder...done
2024-11-27 20:35:00: Setting permissions on persisted data folder...done
2024-11-27 20:35:00: GPU support                                                           
2024-11-27 20:35:00: CUDA (NVIDIA) Present: No
2024-11-27 20:35:02: ROCm (AMD) Present:    (attempt to install rocminfo... ) No
2024-11-27 20:35:02: MPS (Apple) Present:   No
2024-11-27 20:35:03: Reading module settings.......done
2024-11-27 20:35:03: Processing module ALPR 3.3.0                                          
2024-11-27 20:35:03: Internal module install
2024-11-27 20:35:03: Installing Python 3.8
2024-11-27 20:35:03: Python 3.8 is already installed
2024-11-27 20:35:07: Ensuring PIP in base python install...  done
2024-11-27 20:35:09: Upgrading PIP in base python install... done
2024-11-27 20:35:09: Installing Virtual Environment tools for Linux...
2024-11-27 20:35:51: Searching for python3-pip python3-setuptools python3.8...installing...   done
2024-11-27 20:36:31: Creating Virtual Environment (Local)... done
2024-11-27 20:36:31: Checking for Python 3.8...(Found Python 3.8.20) All good
2024-11-27 20:37:55: Upgrading PIP in virtual environment... done
2024-11-27 20:38:31: Installing updated setuptools in venv... done
2024-11-27 20:38:31: deb http://security.ubuntu.com/ubuntu focal-security main
2024-11-27 20:38:36: Searching for libssl1.1...installing...   done
2024-11-27 20:38:36: Ensuring symlinks are created...Done
2024-11-27 20:38:39: Downloading OCR models...Expanding... done.
2024-11-27 20:38:39: Moving contents of ocr-en-pp_ocrv4-paddle.zip to paddleocr...done.
2024-11-27 20:38:39: Installing Python packages for License Plate Reader
2024-11-27 20:38:39: Installing GPU-enabled libraries: No
2024-11-27 20:38:40: Searching for python3-pip...All good.
2024-11-27 20:38:41: Ensuring PIP compatibility... done
2024-11-27 20:38:41: Python packages will be specified by requirements.linux.txt
2024-11-27 20:39:13:   - Installing NumPy, a package for scientific computing... (✅ checked) done
2024-11-27 20:40:47:   - Installing PaddelPaddle, the Deep Learning platform... (✅ checked) done
2024-11-27 20:46:03:   - Installing PaddleOCR, the OCR toolkit based on PaddlePaddle... (✅ checked) done
2024-11-27 20:46:24:   - Installing imutils, the image utilities library... (✅ checked) done
2024-11-27 20:47:03:   - Installing the CodeProject.AI SDK... (✅ checked) done
2024-11-27 20:47:03: Scanning modulesettings for downloadable models...No models specified
2024-11-27 20:47:03: Executing post-install script for License Plate Reader
2024-11-27 20:47:03: Applying PaddleOCR patch
2024-11-27 20:47:34: Self test: Self-test passed
2024-11-27 20:47:34: Module setup time 00:12:32
2024-11-27 20:47:34:                 Setup complete                                        
2024-11-27 20:47:34: Total setup time 00:12:35
```

**Comment by DeFlanko** [comment]
Hi @ChrisMaunder , still only CPU mode

```powershell
docker run --name CodeProject.AI-CUDA12-2.9.4 -d -p 32168:32168 --gpus all --mount type=bind,source=C:\ProgramData\CodeProject\AI\docker\data,target=/etc/codeproject/ai --mount type=bind,source=C:\ProgramData\CodeProject\AI\docker\modules,target=/app/modules --mount type=bind,source=C:\ProgramData\CodeProject\AI\docker\modules\ObjectDetectionYOLOv5-6.2\custom-models,target=/app/preinstalled-modules/ObjectDetectionYolo/custom-models,readonly codeproject/ai-server:cuda12_2-2.9.4
```

![image](https://github.com/user-attachments/assets/a0a3ef16-4d9d-4f0f-b0fb-80673ffe705b)

**Comment by DeFlanko** [comment]
Oh , wait you did say CUDA 11.... trying that now:
```powershell
docker run --name CodeProject.AI-CUDA11-2.9.4 -d -p 32168:32168 --gpus all --mount type=bind,source=C:\ProgramData\CodeProject\AI\docker\data,target=/etc/codeproject/ai --mount type=bind,source=C:\ProgramData\CodeProject\AI\docker\modules,target=/app/modules --mount type=bind,source=C:\ProgramData\CodeProject\AI\docker\modules\ObjectDetectionYOLOv5-6.2\custom-models,target=/app/preinstalled-modules/ObjectDetectionYolo/custom-models,readonly codeproject/ai-server:cuda11_8-2.9.4
```

**Comment by YuCHii26** [comment]
### GPU Not Detected by ALPR Module in CodeProject.AI

I faced the same issue where the **ALPR module** in CodeProject.AI could not use the GPU, even though PaddlePaddle's standalone test script successfully detected and utilized the GPU. Specifically:

---

### 1. **PaddlePaddle Standalone Test**  
When running PaddlePaddle's standalone Python script, the GPU is detected and works without issues:

```bash
(venv) root@XXXXX:/bin/codeproject.ai-server-2.9.5/modules/ALPR# python -c "import paddle; paddle.utils.run_check()"
Running verify PaddlePaddle program ... 
I1217 13:00:40.887516 3453805 program_interpreter.cc:212] New Executor is Running.
W1217 13:00:40.888669 3453805 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 90. It is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1217 13:00:40.888867 3453805 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.4, Runtime API Version: 12.0
W1217 13:00:40.890385 3453805 gpu_resources.cc:164] device: 0, cuDNN Version: 9.5.
I1217 13:00:41.266033 3453805 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```
### 2. ALPR Module Failing GPU Self-Checks

However, when running the ALPR module within CodeProject.AI, it fails GPU self-checks and defaults to CPU.
To diagnose the issue, I added additional logging to the `ALPR_adapter.py` file to capture PaddlePaddle’s GPU detection status:
```logg
2024-12-17 12:05:40,632 - INFO - Initial GPU Detection: hasPaddleGPU = False
2024-12-17 12:05:40,632 - INFO - Final GPU Status: use_gpu = False
2024-12-17 12:05:40,632 - INFO - Using CPU for inference.
```
### 3. Suspecting PaddlePaddle Version Mismatch

I suspected the self-check failures were due to a version mismatch of PaddlePaddle. I removed the existing version and installed the latest GPU-compatible version of PaddlePaddle using the following command:



```bash
python -m pip install paddlepaddle-gpu==2.6.2.post120 -i https://www.paddlepaddle.org.cn/packages/stable/cu120/
```
Unfortunately, this did not resolve the issue.



### 4. Solution: Forcing GPU Usage in ALPR Adapter

To work around this issue, I directly modified the `ALPR_adapter.py` script to force GPU usage and bypass the internal GPU self-check logic.

Steps to Fix:
	1.	Open the ALPR_adapter.py file located at:
```/bin/codeproject.ai-server-2.9.5/modules/ALPR/ALPR_adapter.py```
	2.	Find the initialise() method and add the following lines:
	
```python
# Force GPU usage, bypassing self-check logic

self.opts.use_gpu = True  # <- This forces GPU ON
self.inference_device = "GPU"
self.inference_library = "CUDA"
```
### 5. Testing and Results

After applying the fix, the ALPR module successfully utilized the GPU for inference:
```
2024-12-17 12:44:43,225 - INFO - Initial GPU Detection: hasPaddleGPU = True
2024-12-17 12:44:43,225 - INFO - Final GPU Status: use_gpu = True
2024-12-17 12:44:43,225 - INFO - Using GPU for inference.
2024-12-17 12:44:44,992 - INFO - ALPR Adapter Initialization completed.
----
2024-12-17 13:14:55,210 - INFO - Starting plate number detection...
2024-12-17 13:14:55,728 - INFO - Detection completed: Found Plate: 2528 WZ
2024-12-17 13:14:55,744 - INFO - Updated statistics: numItemsFound = 11
```

### Summary

By forcing GPU usage in the ALPR adapter, the module bypasses the failing PaddlePaddle GPU self-check and successfully leverages the GPU for inference.

<img width="1293" alt="SCR-20241217-mfju" src="https://github.com/user-attachments/assets/a1d0519b-fe1f-4cd1-b228-5bed8924aaf7" />

**Comment by romong** [comment]
> ### GPU Not Detected by ALPR Module in CodeProject.AI
> I faced the same issue where the **ALPR module** in CodeProject.AI could not use the GPU, even though PaddlePaddle's standalone test script successfully detected and utilized the GPU. Specifically:
> 
> ### 1. **PaddlePaddle Standalone Test**
> When running PaddlePaddle's standalone Python script, the GPU is detected and works without issues:
> 
> ```shell
> (venv) root@XXXXX:/bin/codeproject.ai-server-2.9.5/modules/ALPR# python -c "import paddle; paddle.utils.run_check()"
> Running verify PaddlePaddle program ... 
> I1217 13:00:40.887516 3453805 program_interpreter.cc:212] New Executor is Running.
> W1217 13:00:40.888669 3453805 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 90. It is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
> W1217 13:00:40.888867 3453805 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.4, Runtime API Version: 12.0
> W1217 13:00:40.890385 3453805 gpu_resources.cc:164] device: 0, cuDNN Version: 9.5.
> I1217 13:00:41.266033 3453805 interpreter_util.cc:624] Standalone Executor is Used.
> PaddlePaddle works well on 1 GPU.
> PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
> ```
> 
> ### 2. ALPR Module Failing GPU Self-Checks
> However, when running the ALPR module within CodeProject.AI, it fails GPU self-checks and defaults to CPU. To diagnose the issue, I added additional logging to the `ALPR_adapter.py` file to capture PaddlePaddle’s GPU detection status:
> 
> ```
> 2024-12-17 12:05:40,632 - INFO - Initial GPU Detection: hasPaddleGPU = False
> 2024-12-17 12:05:40,632 - INFO - Final GPU Status: use_gpu = False
> 2024-12-17 12:05:40,632 - INFO - Using CPU for inference.
> ```
> 
> ### 3. Suspecting PaddlePaddle Version Mismatch
> I suspected the self-check failures were due to a version mismatch of PaddlePaddle. I removed the existing version and installed the latest GPU-compatible version of PaddlePaddle using the following command:
> 
> ```shell
> python -m pip install paddlepaddle-gpu==2.6.2.post120 -i https://www.paddlepaddle.org.cn/packages/stable/cu120/
> ```
> 
> Unfortunately, this did not resolve the issue.
> 
> ### 4. Solution: Forcing GPU Usage in ALPR Adapter
> To work around this issue, I directly modified the `ALPR_adapter.py` script to force GPU usage and bypass the internal GPU self-check logic.
> 
> Steps to Fix: 1. Open the ALPR_adapter.py file located at: `/bin/codeproject.ai-server-2.9.5/modules/ALPR/ALPR_adapter.py` 2. Find the initialise() method and add the following lines:
> 
> ```python
> # Force GPU usage, bypassing self-check logic
> 
> self.opts.use_gpu = True  # <- This forces GPU ON
> self.inference_device = "GPU"
> self.inference_library = "CUDA"
> ```
> 
> ### 5. Testing and Results
> After applying the fix, the ALPR module successfully utilized the GPU for inference:
> 
> ```
> 2024-12-17 12:44:43,225 - INFO - Initial GPU Detection: hasPaddleGPU = True
> 2024-12-17 12:44:43,225 - INFO - Final GPU Status: use_gpu = True
> 2024-12-17 12:44:43,225 - INFO - Using GPU for inference.
> 2024-12-17 12:44:44,992 - INFO - ALPR Adapter Initialization completed.
> ----
> 2024-12-17 13:14:55,210 - INFO - Starting plate number detection...
> 2024-12-17 13:14:55,728 - INFO - Detection completed: Found Plate: 2528 WZ
> 2024-12-17 13:14:55,744 - INFO - Updated statistics: numItemsFound = 11
> ```
> 
> ### Summary
> By forcing GPU usage in the ALPR adapter, the module bypasses the failing PaddlePaddle GPU self-check and successfully leverages the GPU for inference.
> 
> <img alt="SCR-20241217-mfju" width="1293" src="https://private-user-images.githubusercontent.com/147174356/396365071-a1d0519b-fe1f-4cd1-b228-5bed8924aaf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzcwNTgsIm5iZiI6MTczNDQzNjc1OCwicGF0aCI6Ii8xNDcxNzQzNTYvMzk2MzY1MDcxLWExZDA1MTliLWZlMWYtNGNkMS1iMjI4LTViZWQ4OTI0YWFmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxMTU5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTZhYTdmMjZkMmJiODUwMmRhYTBhNGIxZmVlMjNhMjE2OTEwYjBmOTQ1Y2Y2NmY2NzNjMTg0YjExN2JkMWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FJvn1Tg8lr6_Hhm1Upirta9LIjvMlLnFRwxLo7Mp8u8">

I forced GPU usage per your instruction, then LPR showed GPU(CUDA), but there was no difference in detection time between CPU and GPU(CUDA).  Looks like it does not actually use GPU for detection.

When I ran PaddlePaddle stand alone test, PaddlePaddle still used CPU only:

(venv) root@frigate:/var/lib/docker/overlay2/b0b56b4291ce1c0165584019139b902bce18cca042727d831d923409568e03d4/diff/app/modules/ALPR# python3 -c "import paddle; paddle.utils.run_check()"
Running verify PaddlePaddle program ... 
I1217 04:02:38.141630 44582 program_interpreter.cc:212] New Executor is Running.
I1217 04:02:38.150501 44582 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by DeFlanko** [comment]
> ### GPU Not Detected by ALPR Module in CodeProject.AI
> I faced the same issue where the **ALPR module** in CodeProject.AI could not use the GPU, even though PaddlePaddle's standalone test script successfully detected and utilized the GPU. Specifically:
> 
> ### 1. **PaddlePaddle Standalone Test**
> When running PaddlePaddle's standalone Python script, the GPU is detected and works without issues:
> 
> ```shell
> (venv) root@XXXXX:/bin/codeproject.ai-server-2.9.5/modules/ALPR# python -c "import paddle; paddle.utils.run_check()"
> Running verify PaddlePaddle program ... 
> I1217 13:00:40.887516 3453805 program_interpreter.cc:212] New Executor is Running.
> W1217 13:00:40.888669 3453805 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 90. It is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
> W1217 13:00:40.888867 3453805 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.4, Runtime API Version: 12.0
> W1217 13:00:40.890385 3453805 gpu_resources.cc:164] device: 0, cuDNN Version: 9.5.
> I1217 13:00:41.266033 3453805 interpreter_util.cc:624] Standalone Executor is Used.
> PaddlePaddle works well on 1 GPU.
> PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
> ```
> 
> ### 2. ALPR Module Failing GPU Self-Checks
> However, when running the ALPR module within CodeProject.AI, it fails GPU self-checks and defaults to CPU. To diagnose the issue, I added additional logging to the `ALPR_adapter.py` file to capture PaddlePaddle’s GPU detection status:
> 
> ```
> 2024-12-17 12:05:40,632 - INFO - Initial GPU Detection: hasPaddleGPU = False
> 2024-12-17 12:05:40,632 - INFO - Final GPU Status: use_gpu = False
> 2024-12-17 12:05:40,632 - INFO - Using CPU for inference.
> ```
> 
> ### 3. Suspecting PaddlePaddle Version Mismatch
> I suspected the self-check failures were due to a version mismatch of PaddlePaddle. I removed the existing version and installed the latest GPU-compatible version of PaddlePaddle using the following command:
> 
> ```shell
> python -m pip install paddlepaddle-gpu==2.6.2.post120 -i https://www.paddlepaddle.org.cn/packages/stable/cu120/
> ```
> 
> Unfortunately, this did not resolve the issue.
> 
> ### 4. Solution: Forcing GPU Usage in ALPR Adapter
> To work around this issue, I directly modified the `ALPR_adapter.py` script to force GPU usage and bypass the internal GPU self-check logic.
> 
> Steps to Fix: 1. Open the ALPR_adapter.py file located at: `/bin/codeproject.ai-server-2.9.5/modules/ALPR/ALPR_adapter.py` 2. Find the initialise() method and add the following lines:
> 
> ```python
> # Force GPU usage, bypassing self-check logic
> 
> self.opts.use_gpu = True  # <- This forces GPU ON
> self.inference_device = "GPU"
> self.inference_library = "CUDA"
> ```
> 
> ### 5. Testing and Results
> After applying the fix, the ALPR module successfully utilized the GPU for inference:
> 
> ```
> 2024-12-17 12:44:43,225 - INFO - Initial GPU Detection: hasPaddleGPU = True
> 2024-12-17 12:44:43,225 - INFO - Final GPU Status: use_gpu = True
> 2024-12-17 12:44:43,225 - INFO - Using GPU for inference.
> 2024-12-17 12:44:44,992 - INFO - ALPR Adapter Initialization completed.
> ----
> 2024-12-17 13:14:55,210 - INFO - Starting plate number detection...
> 2024-12-17 13:14:55,728 - INFO - Detection completed: Found Plate: 2528 WZ
> 2024-12-17 13:14:55,744 - INFO - Updated statistics: numItemsFound = 11
> ```
> 
> ### Summary
> By forcing GPU usage in the ALPR adapter, the module bypasses the failing PaddlePaddle GPU self-check and successfully leverages the GPU for inference.
> 
> <img alt="SCR-20241217-mfju" width="1293" src="https://private-user-images.githubusercontent.com/147174356/396365071-a1d0519b-fe1f-4cd1-b228-5bed8924aaf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NTEyNDksIm5iZiI6MTczNDQ1MDk0OSwicGF0aCI6Ii8xNDcxNzQzNTYvMzk2MzY1MDcxLWExZDA1MTliLWZlMWYtNGNkMS1iMjI4LTViZWQ4OTI0YWFmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNTU1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmU2MDQ0ZGI4NmQ5YTRkMDYzZGRlYjBiMWIyMmRkNWRkNDZmZWFhZGU0ZmU5MjgyNzMwMWMwYzk4ZGQ1MzQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dqVRQN_qpnOvOkBQBvHUngzS27o1hKFrQljxvYs0X-4">

Can you make a pull request for the py edits you have? maybe Chris will approve it ...

**Comment by ChrisMaunder** [comment]
@YuCHii26 Which operating system and GPU?

**Comment by ChrisMaunder** [comment]
GPU support for Linux is deliberately disabled.

To enable it, simply set 'installGpu": true in `modulesettings.linux.json` and rerun the setup. There's no need to hardwire and bypass the GPU check and reporting that's being done.

The issue is, at least on my machine, that while you can install GPU, you can run the test, and you can get the confidence building message, you also get:

```
    return _broadcast_in_dygraph(
  File "/mnt/c/Dev/CodeProject/CodeProject.AI-Modules/CodeProject.AI-ALPR/bin/ubuntu/python38/venv/lib/python3.8/site-packages/paddle/distributed/communication/stream/broadcast.py", line 32, in _broadcast_in_dygraph
    task = group.process_group.broadcast(tensor, src_rank_in_group, sync_op)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:312)
  ```

I spent days trying to sort this out and eventually gave up. PaddlePaddle is very, very fragile. I'm leaving any further development of this module to the community.
