### ISSUE TITLE
APLR does not recognize California Black and Yellow plates

### ISSUE THREAD

**Issue by DeFlanko** [codeproject/CodeProject.AI-ALPR#2]
Using this image, humans can read my license plate. APLR struggles to find it. 

![Cam200 20241110_143805241 20](https://github.com/user-attachments/assets/8f0d1239-8874-44b7-aa47-6d34024994e4)

![image](https://github.com/user-attachments/assets/411413a0-6cca-4766-a3a4-b9a56c52fd73)

![image](https://github.com/user-attachments/assets/327a2175-923a-443d-9001-94c84a4252dc)

![image](https://github.com/user-attachments/assets/06ef14be-97ff-48c9-b682-d7e56b72d644)

![image](https://github.com/user-attachments/assets/e7c26cf9-d07c-4d50-a5ac-15d9711f0f17)

![image](https://github.com/user-attachments/assets/c204676c-b4a0-4f66-9a99-cd202652b659)

**Comment by DeFlanko** [comment]
![image](https://github.com/user-attachments/assets/56b35cb2-b214-4956-8ae8-08aa62d8407b)

**Comment by MikeLud** [comment]
Overview cameras are not good for ALPR
You can try creating a clone of this camera and then create an area of interest where you want to read the license plates. Also make sure you have **Use main stream if available** checked

![image](https://github.com/user-attachments/assets/76bb5e5e-5456-4003-b19f-d5748da29ba8)

![image](https://github.com/user-attachments/assets/b47d519c-6bc7-42be-8706-bc53be844f9a)

![image](https://github.com/user-attachments/assets/156b9297-d59b-4579-82ff-5caf745d409c)

**Comment by DeFlanko** [comment]
Thanks mike trying this over the holiday.
