### ISSUE TITLE
LicensePlate module won't install under docker

### ISSUE THREAD

**Issue by brianegge** [codeproject/CodeProject.AI-ALPR#3]
**Area of Concern**
- [ ] Server
- [X] Behaviour of one or more Modules License Plate Reader
- [X] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**

**Expected behavior**

**Screenshots**

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.2.4-Beta (docker gpu latest)
 - OS: Ubuntu 22.04
 - System RAM 32Gb
 - GPU (if available) GeForce RTX 3080

**Additional context**
```
08:07:42:ALPR: Checking for ROCm support... Done
08:07:42:ALPR: sh: 1: lsmod: not found
08:07:42:ALPR:              Installing CodeProject.AI Analysis Module                
08:07:42:ALPR: ======================================================================
08:07:42:ALPR:                    CodeProject.AI Installer                           
08:07:42:ALPR: ======================================================================
08:07:42:ALPR: 6.07 GiB  available
08:07:42:ALPR: Installing curl...
08:07:42:ALPR: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
08:07:43:ALPR: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.81.0-1ubuntu1.13_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
08:07:43:ALPR: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.81.0-1ubuntu1.13_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
08:07:43:ALPR: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
08:07:43:Module ALPR installed successfully.
08:07:43:
08:07:43:Module 'License Plate Reader' 2.6 (ID: ALPR)
08:07:43:Module Path:   /app/modules/ALPR
08:07:43:AutoStart:     True
08:07:43:Queue:         alpr_queue
08:07:43:Installer exited with code 10
08:07:43:Platforms:     windows,linux,macos,macos-arm64
08:07:43:GPU:           Support disabled
08:07:43:Parallelism:   0
08:07:43:Accelerator:
08:07:43:Half Precis.:  enable
08:07:43:Runtime:       python38
08:07:43:Runtime Loc:   Local
08:07:43:FilePath:      ALPR_adapter.py
08:07:43:Pre installed: False
08:07:43:Start pause:   1 sec
08:07:43:LogVerbosity:
08:07:43:Valid:         True
08:07:43:Environment Variables
08:07:43:AUTO_PLATE_ROTATE            = True
08:07:43:OCR_OPTIMAL_CHARACTER_HEIGHT = 60
08:07:43:OCR_OPTIMAL_CHARACTER_WIDTH  = 36
08:07:43:OCR_OPTIMIZATION             = True
08:07:43:PLATE_CONFIDENCE             = 0.7
08:07:43:PLATE_RESCALE_FACTOR         = 2
08:07:43:PLATE_ROTATE_DEG             = 0
08:07:43:
08:07:43:Error trying to start License Plate Reader (ALPR_adapter.py)
08:07:43:An error occurred trying to start process '/app/modules/ALPR/bin/linux/python38/venv/bin/python3' with working directory '/app/modules/ALPR'. No such file or directory
08:07:43:   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at CodeProject.AI.Server.Modules.ModuleProcessServices.StartProcess(ModuleConfig module)
08:07:43:Module ALPR started successfully.
08:07:43:Please check the CodeProject.AI installation completed successfully
08:07:44:Call to Install on module ALPR has completed.
```

**Comment by ChrisMaunder** [comment]
Docker 2.9.6 and ALPR 3.3.4 released. Please try them for docker issues.

**Comment by xavan83** [comment]
Thank you fo your work
But the last available docker image is only for raspberry and arm. Can you publish the cpu one?

**Comment by andreasengler83** [comment]
hello guy i am struggeling on my raspberry (Debian GNU/Linux 12 bookworm): I run ai server in docker codeproject/ai-server:rpi64  
during installation i get these errors: 

`18:58:38:ALPR:   - Installing PaddelPaddle, the Deep Learning platform...Checking ...Check done...Installing paddlepaddle==2.6.0... (❌ failed check) done
18:59:31:ALPR:   - Installing PaddleOCR, the OCR toolkit based on PaddlePaddle...Checking ...Check done...Installing paddleocr==2.7.0.3... (❌ failed check) done
`

and when the adapter starts 
`19:00:25:Started License Plate Reader module
19:00:26:ALPR_adapter.py: Traceback (most recent call last):
19:00:26:ALPR_adapter.py:   File "/app/modules/ALPR/ALPR_adapter.py", line 11, in 
19:00:26:ALPR_adapter.py:     from ALPR import init_detect_platenumber, detect_platenumber
19:00:26:ALPR_adapter.py:   File "/app/modules/ALPR/ALPR.py", line 17, in 
19:00:26:ALPR_adapter.py:     from paddleocr import PaddleOCR
19:00:26:ALPR_adapter.py: ImportError: cannot import name 'PaddleOCR' from 'paddleocr' (unknown location)
19:00:27:Module ALPR has shutdown`

Can anybody help ?
