### ISSUE TITLE
Liicense Plate Reader 3.3.0 under CPAI version 2.8 and 2.65 "Failed to Start"

### ISSUE THREAD

**Issue by dslackhome** [codeproject/CodeProject.AI-ALPR#5]
**Area of Concern**
- [ ] Server
- [x] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
In an attempt to get my Nvidia 1650 GPU graphics card to work with Yolo5 6.2 and License Plate Reader, I installed Nvidia Cuda 11.8. Cudnn 9.3. CPAI version 2.6.5, then CPAI server version 2.8.  CPAI server version 2.8 got the Yolo5 6.2 to see and use the GPU, but License Plate Reader is failing to load and stops after 1 minute or less of being up.  This License Plate Reader failed to start was also present in the CPAI server 2.65 version as well.  My previous setup (Yolo5 6.2 and License Plate Reader was stable when on CPAI 2.6.5 using a Radeon graphics card and CPU only on the CPAI server.  This License Plate Reader problem started after I switched to the Nvidia 1650 graphics card and started installing various CUDA versions (tried latest 12.6?, 11.7 and eventually settled on CUDA 11.8.

The license plate reader "failed to start" error seems to be centered around the log error messages related to:
ALPR_adapter.py
ALPR.py

<img width="956" alt="image" src="https://github.com/user-attachments/assets/6609c26d-3b2c-4e65-bfcc-245ae604a842">
![Screenshot 2024-08-27 120708](https://github.com/user-attachments/assets/141267ae-052c-4017-8fb9-854bf3d5242c)

**Expected behavior**
License Plate Reader should start and stay up and not fail to start.
License Plate Reader should also use GPU rather than CPU since a usable Nvidia 1650 GPU is present and setup.

and the missing module utils.tools

ALPR_adapter.py:     import utils.tools as tool
ALPR_adapter.py: ModuleNotFoundError: No module named 'utils.tools'

(see screen shot of log below)

**Screenshots**
11:48:08:Restarting License Plate Reader to apply settings change
11:48:08:
11:48:08:Module 'License Plate Reader' 3.3.0 (ID: ALPR)
11:48:08:Valid:            True
11:48:08:Module Path:      <root>\modules\ALPR
11:48:08:Module Location:  Internal
11:48:08:AutoStart:        True
11:48:08:Queue:            alpr_queue
11:48:08:Runtime:          python3.9
11:48:08:Runtime Location: Local
11:48:08:FilePath:         ALPR_adapter.py
11:48:08:Start pause:      3 sec
11:48:08:Parallelism:      0
11:48:08:LogVerbosity:
11:48:08:Platforms:        all,!windows-arm64
11:48:08:GPU Libraries:    installed if available
11:48:08:GPU:              use if supported
11:48:08:Accelerator:
11:48:08:Half Precision:   enable
11:48:08:Environment Variables
11:48:08:AUTO_PLATE_ROTATE            = True
11:48:08:CROPPED_PLATE_DIR            = <root>\Server\wwwroot
11:48:08:MIN_COMPUTE_CAPABILITY       = 6
11:48:08:MIN_CUDNN_VERSION            = 7
11:48:08:OCR_OPTIMAL_CHARACTER_HEIGHT = 60
11:48:08:OCR_OPTIMAL_CHARACTER_WIDTH  = 30
11:48:08:OCR_OPTIMIZATION             = True
11:48:08:PLATE_CONFIDENCE             = 0.7
11:48:08:PLATE_RESCALE_FACTOR         = 2
11:48:08:PLATE_ROTATE_DEG             = 0
11:48:08:REMOVE_SPACES                = False
11:48:08:ROOT_PATH                    = <root>
11:48:08:SAVE_CROPPED_PLATE           = False
11:48:08:
11:48:08:Started License Plate Reader module
11:48:08:ALPR_adapter.py: Traceback (most recent call last):
11:48:08:ALPR_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\ALPR\ALPR_adapter.py", line 11, in 
11:48:08:ALPR_adapter.py:     from ALPR import init_detect_platenumber, detect_platenumber
11:48:08:ALPR_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\ALPR\ALPR.py", line 7, in 
11:48:08:ALPR_adapter.py:     import utils.tools as tool
11:48:08:ALPR_adapter.py: ModuleNotFoundError: No module named 'utils.tools'
11:48:08:Module ALPR has shutdown
11:48:08:ALPR_adapter.py: has exited

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.8 (2.6.5 also does not work)
 - CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz   3.00 GHz
 - OS: Windows 11
 - System RAM 32Gb
 - GPU : GeForce GTX 1650
 - GPU RAM: 4Gb

**Additional context**

**Comment by coderdude1** [comment]
> @coderdude1 What version of CUDA are you on? 11.X or 12.X? I have a new release pending that doesn't fix the paddlepaddle-gpu to a specific version and that's working great on 12.x. If it works on 11.x then I'll update the req.txt for 11.X and include that in the next rev
Howdy!  I'm running 11.x, with a GTX1080.  Thanks!

**Comment by ChrisMaunder** [comment]
Please try the latest docker.
