### ISSUE TITLE
Docker 2.9.4 path changed from /app/modules/ALPR/bin/linux to ubuntu

### ISSUE THREAD

**Issue by idontcare99999** [codeproject/CodeProject.AI-ALPR#9]
Fresh docker install of 2.9.4 fails with: 

> 09:58:30:Error trying to start License Plate Reader (ALPR_adapter.py)
> 09:58:30:Error is: An error occurred trying to start process '/app/modules/ALPR/bin/linux/python38/venv/bin/python3' with working directory '/app/modules/ALPR'. No such file or directory
> 09:58:30:   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at CodeProject.AI.Server.Modules.ModuleProcessServices.StartProcess(ModuleConfig module, String installSummary)

Launching shell within container shows that path has been changed.

ln -s ubuntu linux within /app/modules/ALPR/bin allows successful launch.

**Comment by ChrisMaunder** [comment]
I pushed a bad version of the Docker image. Can you please try pulling it again and giving it another shot?
